grails-app/domain/ferias/Ferias.groovy
package ferias

import br.edu.unirn.Funcionario
import grails.databinding.BindingFormat

/*CLASSE FÉRIAS
PATRYCK HERNANDEZ*/

class Ferias {

    Funcionario funcionario
    String exercicio
    Integer numeroDias
    String feriasJudiciais
    String observacoes
    String justificativa
    Integer numeroParcelas

    static constraints = {

        funcionario()
        exercicio nullable: false
        numeroDias nullable: false
        feriasJudiciais nulable: true
        observacoes nullable: true, maxSize: 320, widget: 'textarea'
        justificativa nullable: true, maxSize: 320, widget: 'textarea'
        numeroParcelas nullable: false, maxSize: 3
        status nullable: true
    }
    static hasMany = [status:Status, parc:Parcelas]

    static mapping = {
        status joinTable:[name:"ferias_status", key:"ferias_id", column:'ferias']
    }

}

grails-app/domain/ferias/Parcelas.groovy
package ferias

import grails.databinding.BindingFormat

class Parcelas {
    @BindingFormat('yyyy-MM-dd')
    Date dataSaida
    @BindingFormat('yyyy-MM-dd')
    Date dataVolta
    String status
    Ferias ferias
    Integer dias
    static constraints = {
        dataSaida(nullable: true)
        dataVolta(nullable: true)
        status()
        dias()
    }

}

grails-app/domain/ferias/Status.groovy
package ferias
/*Classe responsável pelo status de férias do funcionário
PATRYCK HERNANDEZ*/

class Status {

    String descricao
    boolean ativo
    static belongsTo = Ferias
    static constraints = {
        descricao()
        ativo()

    }
}

grails-app/controllers/ferias/FeriasController.groovy
package ferias

import br.edu.unirn.Funcionario
import grails.transaction.Transactional

import java.text.SimpleDateFormat

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class FeriasController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Ferias.list(), model: [feriasCount: Ferias.count()]
    }

    def create() {
        if (params.nome != null) {
            def nome = Funcionario.findByNomeLike("%" + params.nome + "%")
            def fer = Ferias.findByFuncionario(nome)
            def parc = Parcelas.findByFerias(fer)

            if(nome == null && fer == null){
                respond new Ferias(params), view: 'create', model: [name:nome]
                flash.error = 'Funcionário não existe!!'
            }else{
                respond new Ferias(params), view: 'create', model: [fer: fer,parce:parc, nome: nome]
            }

        } else {

            respond new Ferias(params)
        }
    }

    @Transactional
    def save(Ferias ferias) {
        if (ferias == null) {
            notFound()
            return
        }

        Funcionario res = Funcionario.findByNomeLike("%" + params.nome + "%")

        if (res == null) {
            flash.message = "Funcionário não existe!"
        } else {
            ferias.funcionario = res
        }
       /* def feri_t = Ferias.findByFuncionario(res)
        def prest = Parcelas.findByFerias(feri_t)
        if(prest != null) {
            ferias.inicio = prest.dataSaida
            ferias.fim = prest.dataVolta
        }*/
        ferias.save(flush: true, failOnError: true)

        Parcelas parc = new Parcelas()
        //pega férias funcionário
        def feria = Ferias.findByFuncionario(res)
        def numParc = Integer.parseInt(params.numeroParcelas)
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy")

        if (numParc == 1) {
            def data = formataData(params.data1, params.dia1)
            def data1 = params.data1
            def dataTes = formato.parse(data1)
            parc.dataSaida = dataTes
            parc.dataVolta = data
            parc.dias = Integer.parseInt(params.dia1)
            parc.ferias = feria
            parc.status = "Aguardando Aprovação"
            parc.save(flush: true)

        } else if (numParc == 2) {
            def data = formataData(params.data1, params.dia1)
            def data1 = params.data1
            def dataTes = formato.parse(data1)
            parc.dataSaida = dataTes
            parc.dataVolta = data
            parc.dias = Integer.parseInt(params.dia1)
            parc.ferias = feria
            parc.status = "Aguardando Aprovação"
            parc.save(flush: true)

            Parcelas parce = new Parcelas()
            def data2 = formataData(params.data2, params.dia2)
            def data3 = params.data2
            def dataTesv = formato.parse(data3)
            parce.dataSaida = dataTesv
            parce.dataVolta = data2
            parce.dias = Integer.parseInt(params.dia2)
            parce.ferias = feria
            parce.status = "Aguardando Aprovação"
            parce.save(flush: true)
        } else {
            def data = formataData(params.data1, params.dia1)
            def data1 = params.data1
            def dataTes = formato.parse(data1)
            parc.dataSaida = dataTes
            parc.dataVolta = data
            parc.dias = Integer.parseInt(params.dia1)
            parc.ferias = feria
            parc.status = "Aguardando Aprovação"
            parc.save(flush: true)

            Parcelas parce = new Parcelas()
            def data2 = formataData(params.data2, params.dia2)
            def data3 = params.data2
            def dataTesv = formato.parse(data3)
            parce.dataSaida = dataTesv
            parce.dataVolta = data2
            parce.dias = Integer.parseInt(params.dia2)
            parce.ferias = feria
            parce.status = "Aguardando Aprovação"
            parce.save(flush: true)

            Parcelas parcel = new Parcelas()
            def data4 = formataData(params.data3, params.dia3)
            def dataNes = params.data3
            def dataTest = formato.parse(dataNes)
            parcel.dataSaida = dataTest
            parcel.dataVolta = data4
            parcel.dias = Integer.parseInt(params.dia3)
            parcel.ferias = feria
            parcel.status = "Aguardando Aprovação"
            parcel.save(flush: true)

        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'ferias.label', default: 'Ferias'), ferias.id])
                redirect action: "index", method: "GET"
                flash.message= 'Férias cadastradas com sucesso!'
            }
            '*' { respond ferias, [status: CREATED] }
        }
    }

    def formataData(String data, String dia) {

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy")
        Date dataFormatada = formato.parse(data)
        def diaNovo = Integer.parseInt(dia)

        Calendar c = Calendar.getInstance()
        c.setTime(dataFormatada)
        c.add(Calendar.DATE, diaNovo)
        def rese = c.getTime()

        return rese

    }

    def edit(Ferias ferias) {
        respond ferias
    }

    @Transactional
    def update(Ferias ferias) {
        if (ferias == null) {
            notFound()
            return
        }

        if (ferias.hasErrors()) {
            respond ferias.errors, view: 'edit'
            return
        }

        ferias.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ferias.label', default: 'Ferias'), ferias.id])
                redirect action: "index", method: "GET"
            }
            '*' { respond ferias, [status: OK] }
        }
    }

    @Transactional
    def delete(Ferias ferias) {

        if (ferias == null) {
            notFound()
            return
        }
        if (new Ferias()?.properties?.containsKey('ativo')) {
            ferias.ativo = false
            ferias.save flush: true
        } else {
            ferias.delete flush: true
        }


        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ferias.label', default: 'Ferias'), ferias.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'ferias.label', default: 'Ferias'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/ferias/StatusController.groovy
package ferias

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class StatusController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def create() {
        respond new Status(params)
    }

    @Transactional
    def save(Status status) {
        if (status == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (status.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond status.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'status.label', default: 'Status'), status.id])
                redirect action:"index", method:"GET"
            }
            '*' { respond status, [status: CREATED] }
        }
    }

    def edit(Status status) {
        respond status
    }

    @Transactional
    def update(Status status) {
        if (status == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (status.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond status.errors, view:'edit'
            return
        }

        status.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'status.label', default: 'Status'), status.id])
                redirect action:"index", method:"GET"
            }
            '*'{ respond status, [status: OK] }
        }
    }

    @Transactional
    def delete(Status status) {

        if (status == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }
        if(new Status()?.properties?.containsKey('ativo')){
            status.ativo = false
            status.save flush:true
        }else{
            status.delete flush:true
        }


        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'status.label', default: 'Status'), status.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'status.label', default: 'Status'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/ferias/_cadastro.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'ferias.label', default: 'Ferias')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>

</head>

<body>

<div class="row">

    <div class="col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
        </g:if>
        <g:hasErrors bean="${ferias}">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
            </div>
        </g:hasErrors>
        <div class="feria">
            <header class="head"> <h4>
                <i class="fa fa-car" aria-hidden="true"></i>  Férias
            </h4>
            </header>
            <div class="linha"></div>
            <div class="feria2">
                <g:form class="form-horizontal" name="feriasForm" action="save">
                    <fieldset class="form">
                        <f:field bean="ferias" property="exercicio"/>
                        <f:field bean="ferias" property="numeroDias"/>
                        <f:field bean="ferias" property="observacoes"/>
                        <f:field bean="ferias" property="justificativa"/>
                        <f:field bean="ferias" property="feriasJudiciais"/>
                        <f:field bean="ferias" property="numeroParcelas"/>
                    </fieldset>
                </g:form>
            </div>
        </div>
        <div class="panel-footer clearfix form-actions"
             style="margin-top: 25px;background-color: #fff; border-radius: 0;">
            <button type="submit" form="feriasForm" class="btn btn-success btn-sm btn-flat btt">
                <i class="glyphicon glyphicon-ok"></i> <g:message code="default.button.create.label"
                                                                  args="[entityName]"/>
            </button>
        </div>
    </div>
    </div>
</body>
html>

grails-app/views/ferias/_tablee.gsp
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <td><a href="#">Funcionário</a></td>
            <td><a href="#"> Exercício</a></td>
            <td><a href="#">Número de dias</a></td>
            <td><a href="#">Férias Judiciais</a></td>
            <td><a href="#">Observações</a></td>
            <td><a href="#">Justificativa</a></td>
            <td>&nbsp;</td>
        </tr>
        </thead>
        <tbody>

        <g:each in="${feriasList}" var="bean" status="i">

            <td>${bean.funcionario}</td>
            <td>${bean.exercicio}</td>
            <td>${bean.numeroDias}</td>
            <td>${bean.feriasJudiciais}</td>
            <td>${bean.observacoes}</td>
            <td>${bean.justificativa}</td>
            <td>
                <g:form resource="${bean}" method="DELETE">
                    <g:link class="btn btn-primary" action="edit" resource="${bean}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="btn btn-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('Deseja remover mesmo?');" />
                </g:form>
            </td>
            </tr>
        </g:each>
        </tbody>
    </table>
</div>

grails-app/views/ferias/create.gsp
<%@ page import="ferias.Ferias" %>
<!DOCTYPE html>
<html xmlns:v-on="http://www.w3.org/1999/xhtml">
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'ferias.label', default: 'Ferias')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>

</head>

<body>
<div class="row">
    <div class="col-sm-12">
        <g:link class="btn btn-default btn-sm btn-flat pull-right" action="index">
            <i class="glyphicon glyphicon-arrow-left"></i> <g:message code="default.back.label" default="voltar"/>
        </g:link>
    </div>

    <div class="col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
        </g:if>
        <g:hasErrors bean="${ferias}">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
            </div>
        </g:hasErrors>

        <g:if test="${fer != null && parce != null}">
            <div id="tec" class="feria">
            <header class="head"> <h4>
                <i class="fa fa-calendar-check-o" aria-hidden="true"></i>  Período Aquisitivo
            </h4>
            </header>
            <div class="table-responsive tabes">
             <table class=" table table-hover">
                 <thead>
                 <tr class="coli">
                    <td><a href="#">EXERCÍCIO</a></td>
                    <td><a href="#">Dias</a></td>
                    <td><a href="#">Início</a></td>
                     <td><a href="#">Fim</a></td>
                     <td><a href="#">Status</a></td>
                </tr>
                 </thead>
            <g:each in="${fer.list()}" var="item">
                <g:each in="${parce.list()}" var="it">
                <tr>
                    <td>${item.exercicio}</td>
                    <td>${it.dias}</td>
                    <td><g:formatDate format="dd/MM/yyyy" date="${it.dataSaida}"/> </td>
                    <td><g:formatDate format="dd/MM/yyyy" date="${it.dataVolta}"/> </td>
                    <td>${it.status}</td>
                </tr>
                </g:each>
            </g:each>
            </table>
            </div>
                <div class="pagination">
                    <g:paginate total="${fers ?: 0}"/>
                </div>
            </div>

        </g:if>

        <g:if test="${nome == null}">
        <div class="feria">
            <header class="head"> <h4>
                <i class="fa fa-car" aria-hidden="true"></i>  Férias
            </h4>
            </header>
            <g:if test="${flash.error}">
                <div class="erros">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> ${flash.error}
                </div>
            </g:if>
            <div class="linha"></div>
            <div class="feria2">
        <g:form class="form-horizontal" name="feriasForm1" action="create">
            <fieldset class="forms">
               <label>Nome</label>
                <input name="nome" required class="inpts char"/>
            </fieldset>
        </g:form>
                    <button type="submit" form="feriasForm1" class="btn btn-success btn-sm btn-flat btt1">
                        <i class="glyphicon glyphicon-ok"></i> <g:message code="Buscar"
                                                                          args="[entityName]"/>
                    </button>
                </div>

        </div>
        </g:if>

        <g:if test="${nome != null}">
            <div class="row">

                <div class="col-sm-12">
                    <g:if test="${flash.message}">
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            ${flash.message}
                        </div>
                    </g:if>
                    <g:hasErrors bean="${ferias}">
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
                        </div>
                    </g:hasErrors>
                    <div class="feria">
                        <header class="head"> <h4>
                            <i class="fa fa-car" aria-hidden="true"></i>  Férias
                        </h4>
                        </header>
                        <div class="linha"></div>
                        <div class="feria2">
                            <g:form class="form-horizontal" name="feriasForm" action="save">
                                <fieldset class="form">
                                    <g:each in="${nome}" var="nom">
                                        <fieldset class="forms">
                                            <label>Nome</label>
                                            <input type="text" readonly name="nome" class="inpts" value="${nom.nome}"/>
                                        </fieldset>
                                    </g:each>
                                    <f:field bean="ferias" property="exercicio"/>
                                    <f:field bean="ferias" property="numeroDias"/>
                                    <f:field bean="ferias" property="observacoes"/>
                                    <f:field bean="ferias" property="justificativa"/>
                                    <f:field bean="ferias" property="feriasJudiciais"/>
                                    <f:field bean="ferias" property="numeroParcelas"/>
                                    <div class="teste">

                                        <a href="javascript:void(0);" id="bto">Exibir Períodos</a>
                                    </div>
                                    <div id="parc" class="mostPer">
                                        <header class="tit"><h4>
                                            <i class="fa fa-car" aria-hidden="true"></i>  Dados do Parcelamento
                                        </h4>
                                        </header>

                                        <div id="abe" class="diaT">
                                           <div class="loed">
                                               <p>Períodos</p>
                                               <p>Dias</p>
                                               <p>Início</p>
                                               <p>Término</p>
                                           </div>
                                            <label>1º Período</label>
                                            <g:textField class="erf numeric" name="dia1"/>
                                            <g:textField class="dta date" precision="day" name="data1"/>
                                        </div>

                                        <div id="abe2" class="diaT">
                                            <label>2º Período</label>
                                            <g:textField class="erf numeric" name="dia2"/>
                                            <g:textField class="dta date" precision="day" name="data2"/>
                                        </div>

                                        <div id="abe3" class="diaT">
                                            <label>3º Período</label>
                                            <g:textField class="erf numeric" name="dia3"/>
                                            <g:textField class="dta date" precision="day" name="data3"/>
                                        </div>

                                    </div>
                                </fieldset>
                            </g:form>
                        </div>
                    </div>
                    <div class="panel-footer clearfix form-actions"
                         style="margin-top: 25px;background-color: #fff; border-radius: 0;">
                        <button type="submit" form="feriasForm" class="btn btn-success btn-sm btn-flat btt">
                            <i class="glyphicon glyphicon-ok"></i> <g:message code="default.button.create.label"
                                                                              args="[entityName]"/>
                        </button>
                    </div>
                </div>
            </div>
        </g:if>
    </div>
</div>
</body>
<asset:javascript src="application.js" asset-defer=""/>
</html>

grails-app/views/ferias/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'ferias.label', default: 'Ferias')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="row">
    <div class="col-sm-12">

        <h4 style="font-weight: 300;display: inline-block;margin-bottom: 25px;"><g:message code="default.edit.label"
                                                                                           args="[entityName]"/></h4>
        <g:link action="create" class="btn btn-primary btn-flat btn-sm pull-right margin-left-15">
            <i class="glyphicon glyphicon-plus"></i> <g:message code="default.create.label" args="[entityName]"/>
        </g:link>
        <g:link class="btn btn-default btn-sm btn-flat pull-right" action="index"><i
                class="glyphicon glyphicon-arrow-left"></i> <g:message code="default.back.label"
                                                                       default="voltar"/></g:link>
    </div>

    <div class="col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
        </g:if>
        <g:hasErrors bean="${ferias}">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
            </div>
        </g:hasErrors>
        <div class="feria">
            <header class="head"> <h4>
                <i class="fa fa-car" aria-hidden="true"></i>  Férias
            </h4>
            </header>
            <div class="linha"></div>
            <div class="feria2">
        <g:form class="form-horizontal" name="feriasForm" novalidate="novalidate"
                resource="${this.ferias}" method="PUT">
            <g:hiddenField name="version" value="${ferias?.version}"/>
            <fieldset class="form">
                <div class="divnom">
                <div class="labfunc">
                <label>Funcionário</label>
                </div>
                <g:textField name="func" class="inpt5" value="${ferias.funcionario}"/>
                </div>
                <f:field bean="ferias" property="exercicio"/>
                <f:field bean="ferias" property="numeroDias"/>
                <f:field bean="ferias" property="observacoes"/>
                <f:field bean="ferias" property="justificativa"/>
                <f:field bean="ferias" property="feriasJudiciais"/>
                <f:field bean="ferias" property="numeroParcelas"/>
                <div class="teste">
                <a href="javascript:void(0);" id="bto">Exibir Períodos</a>
                </div>
                <div id="parc" class="mostPer">
                    <header class="tit"><h4>
                        <i class="fa fa-car" aria-hidden="true"></i>  Dados do Parcelamento
                    </h4>
                    </header>

                    <div id="abe" class="diaT">
                        <div class="loed">
                            <p>Períodos</p>
                            <p>Dias</p>
                            <p>Início</p>
                            <p>Término</p>
                        </div>
                        <label>1º Período</label>
                        <g:textField class="erf" name="dia1"/>
                        <g:textField class="dta" precision="day" name="data1"/>
                    </div>

                    <div id="abe2" class="diaT">
                        <label>2º Período</label>
                        <g:textField class="erf" name="dia2"/>
                        <g:textField class="dta" precision="day" name="data2"/>
                    </div>

                    <div id="abe3" class="diaT">
                        <label>3º Período</label>
                        <g:textField class="erf" name="dia3"/>
                        <g:textField class="dta" precision="day" name="data3"/>
                    </div>

                </div>
            </fieldset>
        </g:form>
            </div>
        </div>
        <div class="panel-footer clearfix form-actions"
             style="margin-top: 25px;background-color: #fff; border-radius: 0;">
            <button type="submit" form="feriasForm" class="btn btn-success btn-sm btn-flat btt">
                <i class="fa fa-edit"></i> <g:message code="default.button.update.label"
                                                                  args="[entityName]"/>
            </button>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/ferias/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'ferias.label', default: 'Ferias')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
    <button class="sidebar-toggle visible-xs" id="toggle-left-mini-aside">
        <span class="glyphicon glyphicon-align-justify"></span>
    </button>

    <g:if test="${flash.message}">
        <div class="suces">
            <i class="fa fa-check-circle" aria-hidden="true"></i>
            ${flash.message}
        </div>
    </g:if>

    <div class="row">
        <div class="col-sm-12">
            <h4 style="font-weight: 300;display: inline-block;"><g:message code="default.list.label"
                                                                           args="[entityName]"/></h4>
            <g:link action="create" class="btn btn-primary btn-flat btn-sm pull-right">
                <i class="glyphicon glyphicon-plus"></i> <g:message code="default.create.label" args="[entityName]"/>
            </g:link>
        </div>

        <div class="col-sm-12">
           <g:render template="tablee" bean="${feriasList}"/>

            <div class="pagination">
                <g:paginate  total="${feriasCount ?: 4}"/>
            </div>
        </div>
    </div>
</body>
</html>