grails-app/domain/rh/mod/ponto/RegistroPonto.groovy
package rh.mod.ponto

import br.edu.unirn.Funcionario

class RegistroPonto{

  Date entrada
  Date saida
  static belongsTo = [funcionario:Funcionario]


  static  constraints = {

    funcionario()
    entrada()
    saida()



  }


}

grails-app/controllers/rh/mod/ponto/RegistroPontoController.groovy
package rh.mod.ponto

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RegistroPontoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond RegistroPonto.list(), model:[registroPontoCount: RegistroPonto.count()]
    }

    def create() {
        respond new RegistroPonto(params)
    }

    @Transactional
    def save(RegistroPonto registroPonto) {
        if (registroPonto == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (registroPonto.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond registroPonto.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'registroPonto.label', default: 'RegistroPonto'), registroPonto.id])
                redirect action:"index", method:"GET"
            }
            '*' { respond registroPonto, [status: CREATED] }
        }
    }

    def edit(RegistroPonto registroPonto) {
        respond registroPonto
    }

    @Transactional
    def update(RegistroPonto registroPonto) {
        if (registroPonto == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (registroPonto.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond registroPonto.errors, view:'edit'
            return
        }

        registroPonto.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'registroPonto.label', default: 'RegistroPonto'), registroPonto.id])
                redirect action:"index", method:"GET"
            }
            '*'{ respond registroPonto, [status: OK] }
        }
    }

    @Transactional
    def delete(RegistroPonto registroPonto) {

        if (registroPonto == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }
        if(new RegistroPonto()?.properties?.containsKey('ativo')){
            registroPonto.ativo = false
            registroPonto.save flush:true
        }else{
            registroPonto.delete flush:true
        }


        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'registroPonto.label', default: 'RegistroPonto'), registroPonto.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'registroPonto.label', default: 'RegistroPonto'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/registroPonto/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'registroPonto.label', default: 'RegistroPonto')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>

<div class="row">
    <div class="col-sm-12">
        <h4 style="font-weight: 300;display: inline-block;margin-bottom: 25px;">
            <g:message code="default.create.label" args="[entityName]"/>
        </h4>
        <g:link class="btn btn-default btn-sm btn-flat pull-right" action="index">
            <i class="glyphicon glyphicon-arrow-left"></i> <g:message code="default.back.label" default="voltar"/>
        </g:link>
    </div>

    <div class="col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
        </g:if>
        <g:hasErrors bean="${registroPonto}">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
            </div>
        </g:hasErrors>
        <g:form class="form-horizontal" name="registroPontoForm" novalidate="novalidate" action="save">
            <fieldset class="form">
                <f:all bean="registroPonto"/>
            </fieldset>
        </g:form>
        <div class="panel-footer clearfix form-actions"
             style="margin-top: 25px;background-color: #fff; border-radius: 0;">
            <button type="submit" form="registroPontoForm" class="btn btn-success btn-sm btn-flat">
                <i class="glyphicon glyphicon-ok"></i> <g:message code="default.button.create.label"
                                                                  args="[entityName]"/>
            </button>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/registroPonto/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'registroPonto.label', default: 'RegistroPonto')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="row">
    <div class="col-sm-12">
        <h4 style="font-weight: 300;display: inline-block;margin-bottom: 25px;"><g:message code="default.edit.label"
                                                                                           args="[entityName]"/></h4>
        <g:link action="create" class="btn btn-primary btn-flat btn-sm pull-right margin-left-15">
            <i class="glyphicon glyphicon-plus"></i> <g:message code="default.create.label" args="[entityName]"/>
        </g:link>
        <g:link class="btn btn-default btn-sm btn-flat pull-right" action="index"><i
                class="glyphicon glyphicon-arrow-left"></i> <g:message code="default.back.label"
                                                                       default="voltar"/></g:link>
    </div>

    <div class="col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
        </g:if>
        <g:hasErrors bean="${registroPonto}">
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-exclamation-sign"></i> Alguns campos precisam ser corrigidos.
            </div>
        </g:hasErrors>
        <g:form class="form-horizontal" name="registroPontoForm" novalidate="novalidate"
                resource="${this.registroPonto}" method="PUT">
            <g:hiddenField name="version" value="${registroPonto?.version}"/>
            <fieldset class="form">
                <f:all bean="registroPonto"/>
            </fieldset>
        </g:form>
        <div class="panel-footer clearfix form-actions"
             style="margin-top: 25px;background-color: #fff; border-radius: 0;">
            <button type="submit" form="registroPontoForm" class="btn btn-success btn-sm btn-flat">
                <i class="fa fa-edit"></i> <g:message code="default.button.update.label"/>
            </button>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/registroPonto/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'registroPonto.label', default: 'RegistroPonto')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
    <button class="sidebar-toggle visible-xs" id="toggle-left-mini-aside">
        <span class="glyphicon glyphicon-align-justify"></span>
    </button>

    <div class="row">
        <div class="col-sm-12">
            <h4 style="font-weight: 300;display: inline-block;"><g:message code="default.list.label"
                                                                           args="[entityName]"/></h4>
            <g:link action="create" class="btn btn-primary btn-flat btn-sm pull-right">
                <i class="glyphicon glyphicon-plus"></i> <g:message code="default.create.label"
                                                                    args="[entityName]"/>
            </g:link>
        </div>

        <div class="col-sm-12">
            <f:table collection="${registroPontoList}"/>

            <div class="pagination">
                <g:paginate total="${registroPontoCount ?: 0}"/>
            </div>
        </div>
    </div>
</body>
</html>

grails-app/views/registroPonto/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'registroPonto.label', default: 'RegistroPonto')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-registroPonto" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-registroPonto" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="registroPonto" />
            <g:form resource="${this.registroPonto}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.registroPonto}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>